<?php

namespace App\Models;

use CodeIgniter\Model;

/**
 * Base model for all application models.
 *
 * Provides shared functionality: custom string ID generation and a
 * configurable field-hiding mechanism via the $hiddenFields property.
 *
 * @package App\Models
 */
class ApplicationBaseModel extends Model
{
    /**
     * Fields to strip from query results in the afterFind callback.
     *
     * @var array<int, string>
     */
    protected array $hiddenFields = [];

    /**
     * Holds the last ID produced by generateId() or createId().
     *
     * @var string|null
     */
    private ?string $lastGeneratedId = null;

    /**
     * Returns the last ID that was generated by generateId() or createId(),
     * or null if neither has been called yet.
     *
     * @return string|null
     */
    public function getLastGeneratedId(): ?string
    {
        return $this->lastGeneratedId;
    }

    /**
     * Generates a new unique 13-character hex ID, stores it as the last
     * generated ID, and returns it. Use this when you need the ID before the
     * insert callback runs (e.g. to build a related record before inserting).
     *
     * @return string
     */
    public function createId(): string
    {
        $id = substr(bin2hex(random_bytes(7)), 0, 13);
        $this->lastGeneratedId = $id;

        return $id;
    }

    /**
     * Removes fields listed in $hiddenFields from query results.
     *
     * Intended for use as an afterFind callback. Supports all CI4 find
     * methods: find(), first(), findAll(), and findColumn().
     *
     * @param array $data  The callback payload provided by CI4.
     * @return array
     */
    public function prepareOutput(array $data): array
    {
        if (count($this->hiddenFields) === 0) {
            return $data;
        }

        if (!$data['data']) {
            return $data;
        }

        // find() and first() return a single record, not a list — normalise to array.
        $isSingle = in_array($data['method'], ['find', 'first'], true);
        if ($isSingle) {
            $data['data'] = [$data['data']];
        }

        $resultData = [];

        foreach ($data['data'] as $dataItem) {
            foreach ($this->hiddenFields as $attributeToHide) {
                if (is_array($dataItem)) {
                    unset($dataItem[$attributeToHide]);
                } else {
                    unset($dataItem->{$attributeToHide});
                }
            }
            $resultData[] = $dataItem;
        }

        return ['data' => $isSingle ? $resultData[0] : $resultData];
    }

    /**
     * beforeInsert callback: generates and assigns a 13-character hex string
     * primary key when one has not already been provided.
     *
     * @param array $data  The callback payload provided by CI4.
     * @return array
     */
    protected function generateId(array $data): array
    {
        if (empty($data['data']['id'])) {
            $data['data']['id'] = substr(bin2hex(random_bytes(7)), 0, 13);
        }

        $this->lastGeneratedId = $data['data']['id'];

        return $data;
    }
}
