<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AchievementsSeeder extends Seeder
{
    public function run(): void
    {
        $now  = date('Y-m-d H:i:s');
        $sort = 0;

        $data = [
            // --- Exploration ---
            [
                'group_slug'     => 'explorer',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'exploration',
                'title_en'       => 'Explorer',
                'title_ru'       => 'Исследователь',
                'description_en' => 'Create 10 places on the map',
                'description_ru' => 'Создайте 10 мест на карте',
                'icon'           => 'Compass',
                'rules'          => json_encode([['metric' => 'places_created', 'operator' => '>=', 'value' => 10]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'explorer',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'exploration',
                'title_en'       => 'Explorer',
                'title_ru'       => 'Исследователь',
                'description_en' => 'Create 50 places on the map',
                'description_ru' => 'Создайте 50 мест на карте',
                'icon'           => 'Compass',
                'rules'          => json_encode([['metric' => 'places_created', 'operator' => '>=', 'value' => 50]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'explorer',
                'type'           => 'base',
                'tier'           => 'gold',
                'category'       => 'exploration',
                'title_en'       => 'Explorer',
                'title_ru'       => 'Исследователь',
                'description_en' => 'Create 200 places on the map',
                'description_ru' => 'Создайте 200 мест на карте',
                'icon'           => 'Compass',
                'rules'          => json_encode([['metric' => 'places_created', 'operator' => '>=', 'value' => 200]]),
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'wanderer',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'exploration',
                'title_en'       => 'Wanderer',
                'title_ru'       => 'Странник',
                'description_en' => 'Visit 25 places',
                'description_ru' => 'Посетите 25 мест',
                'icon'           => 'Map',
                'rules'          => json_encode([['metric' => 'places_visited', 'operator' => '>=', 'value' => 25]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'wanderer',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'exploration',
                'title_en'       => 'Wanderer',
                'title_ru'       => 'Странник',
                'description_en' => 'Visit 100 places',
                'description_ru' => 'Посетите 100 мест',
                'icon'           => 'Map',
                'rules'          => json_encode([['metric' => 'places_visited', 'operator' => '>=', 'value' => 100]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'wanderer',
                'type'           => 'base',
                'tier'           => 'gold',
                'category'       => 'exploration',
                'title_en'       => 'Wanderer',
                'title_ru'       => 'Странник',
                'description_en' => 'Visit 500 places',
                'description_ru' => 'Посетите 500 мест',
                'icon'           => 'Map',
                'rules'          => json_encode([['metric' => 'places_visited', 'operator' => '>=', 'value' => 500]]),
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],

            // --- Content ---
            [
                'group_slug'     => 'photographer',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'content',
                'title_en'       => 'Photographer',
                'title_ru'       => 'Фотограф',
                'description_en' => 'Upload 20 photos',
                'description_ru' => 'Загрузите 20 фотографий',
                'icon'           => 'Camera',
                'rules'          => json_encode([['metric' => 'photos_uploaded', 'operator' => '>=', 'value' => 20]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'photographer',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'content',
                'title_en'       => 'Photographer',
                'title_ru'       => 'Фотограф',
                'description_en' => 'Upload 100 photos',
                'description_ru' => 'Загрузите 100 фотографий',
                'icon'           => 'Camera',
                'rules'          => json_encode([['metric' => 'photos_uploaded', 'operator' => '>=', 'value' => 100]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'photographer',
                'type'           => 'base',
                'tier'           => 'gold',
                'category'       => 'content',
                'title_en'       => 'Photographer',
                'title_ru'       => 'Фотограф',
                'description_en' => 'Upload 500 photos',
                'description_ru' => 'Загрузите 500 фотографий',
                'icon'           => 'Camera',
                'rules'          => json_encode([['metric' => 'photos_uploaded', 'operator' => '>=', 'value' => 500]]),
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'curator',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'content',
                'title_en'       => 'Curator',
                'title_ru'       => 'Куратор',
                'description_en' => 'Edit 10 places',
                'description_ru' => 'Отредактируйте 10 мест',
                'icon'           => 'Pencil',
                'rules'          => json_encode([['metric' => 'places_edited', 'operator' => '>=', 'value' => 10]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'curator',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'content',
                'title_en'       => 'Curator',
                'title_ru'       => 'Куратор',
                'description_en' => 'Edit 50 places',
                'description_ru' => 'Отредактируйте 50 мест',
                'icon'           => 'Pencil',
                'rules'          => json_encode([['metric' => 'places_edited', 'operator' => '>=', 'value' => 50]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'curator',
                'type'           => 'base',
                'tier'           => 'gold',
                'category'       => 'content',
                'title_en'       => 'Curator',
                'title_ru'       => 'Куратор',
                'description_en' => 'Edit 200 places and write 50 comments',
                'description_ru' => 'Отредактируйте 200 мест и напишите 50 комментариев',
                'icon'           => 'Pencil',
                'rules'          => json_encode([
                    ['metric' => 'places_edited',    'operator' => '>=', 'value' => 200],
                    ['metric' => 'comments_written', 'operator' => '>=', 'value' => 50],
                ]),
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],

            // --- Social ---
            [
                'group_slug'     => 'critic',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'social',
                'title_en'       => 'Critic',
                'title_ru'       => 'Критик',
                'description_en' => 'Give 20 ratings',
                'description_ru' => 'Поставьте 20 оценок',
                'icon'           => 'Star',
                'rules'          => json_encode([['metric' => 'ratings_given', 'operator' => '>=', 'value' => 20]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'critic',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'social',
                'title_en'       => 'Critic',
                'title_ru'       => 'Критик',
                'description_en' => 'Give 100 ratings',
                'description_ru' => 'Поставьте 100 оценок',
                'icon'           => 'Star',
                'rules'          => json_encode([['metric' => 'ratings_given', 'operator' => '>=', 'value' => 100]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'commenter',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'social',
                'title_en'       => 'Commenter',
                'title_ru'       => 'Комментатор',
                'description_en' => 'Write 10 comments',
                'description_ru' => 'Напишите 10 комментариев',
                'icon'           => 'MessageSquare',
                'rules'          => json_encode([['metric' => 'comments_written', 'operator' => '>=', 'value' => 10]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'commenter',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'social',
                'title_en'       => 'Commenter',
                'title_ru'       => 'Комментатор',
                'description_en' => 'Write 50 comments',
                'description_ru' => 'Напишите 50 комментариев',
                'icon'           => 'MessageSquare',
                'rules'          => json_encode([['metric' => 'comments_written', 'operator' => '>=', 'value' => 50]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'commenter',
                'type'           => 'base',
                'tier'           => 'gold',
                'category'       => 'social',
                'title_en'       => 'Commenter',
                'title_ru'       => 'Комментатор',
                'description_en' => 'Write 200 comments',
                'description_ru' => 'Напишите 200 комментариев',
                'icon'           => 'MessageSquare',
                'rules'          => json_encode([['metric' => 'comments_written', 'operator' => '>=', 'value' => 200]]),
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'collector',
                'type'           => 'base',
                'tier'           => 'none',
                'category'       => 'social',
                'title_en'       => 'Collector',
                'title_ru'       => 'Коллекционер',
                'description_en' => 'Add 30 bookmarks',
                'description_ru' => 'Добавьте 30 закладок',
                'icon'           => 'Bookmark',
                'rules'          => json_encode([['metric' => 'bookmarks_added', 'operator' => '>=', 'value' => 30]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],

            // --- Reputation ---
            [
                'group_slug'     => 'trusted',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'reputation',
                'title_en'       => 'Trusted',
                'title_ru'       => 'Доверенный',
                'description_en' => 'Reach a reputation score of 50',
                'description_ru' => 'Достигните репутации 50',
                'icon'           => 'Shield',
                'rules'          => json_encode([['metric' => 'reputation_score', 'operator' => '>=', 'value' => 50]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'trusted',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'reputation',
                'title_en'       => 'Trusted',
                'title_ru'       => 'Доверенный',
                'description_en' => 'Reach a reputation score of 200',
                'description_ru' => 'Достигните репутации 200',
                'icon'           => 'Shield',
                'rules'          => json_encode([['metric' => 'reputation_score', 'operator' => '>=', 'value' => 200]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'trusted',
                'type'           => 'base',
                'tier'           => 'gold',
                'category'       => 'reputation',
                'title_en'       => 'Trusted',
                'title_ru'       => 'Доверенный',
                'description_en' => 'Reach a reputation score of 1000',
                'description_ru' => 'Достигните репутации 1000',
                'icon'           => 'Shield',
                'rules'          => json_encode([['metric' => 'reputation_score', 'operator' => '>=', 'value' => 1000]]),
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'veteran',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'reputation',
                'title_en'       => 'Veteran',
                'title_ru'       => 'Ветеран',
                'description_en' => 'Reach level 5',
                'description_ru' => 'Достигните уровня 5',
                'icon'           => 'Award',
                'rules'          => json_encode([['metric' => 'level_reached', 'operator' => '>=', 'value' => 5]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'veteran',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'reputation',
                'title_en'       => 'Veteran',
                'title_ru'       => 'Ветеран',
                'description_en' => 'Reach level 15',
                'description_ru' => 'Достигните уровня 15',
                'icon'           => 'Award',
                'rules'          => json_encode([['metric' => 'level_reached', 'operator' => '>=', 'value' => 15]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'veteran',
                'type'           => 'base',
                'tier'           => 'gold',
                'category'       => 'reputation',
                'title_en'       => 'Veteran',
                'title_ru'       => 'Ветеран',
                'description_en' => 'Reach level 25',
                'description_ru' => 'Достигните уровня 25',
                'icon'           => 'Award',
                'rules'          => json_encode([['metric' => 'level_reached', 'operator' => '>=', 'value' => 25]]),
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],

            // --- Consistency ---
            [
                'group_slug'     => 'regular',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'consistency',
                'title_en'       => 'Regular',
                'title_ru'       => 'Постоянный',
                'description_en' => 'Be active on 7 different days',
                'description_ru' => 'Будьте активны 7 разных дней',
                'icon'           => 'Clock',
                'rules'          => json_encode([['metric' => 'days_active', 'operator' => '>=', 'value' => 7]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'regular',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'consistency',
                'title_en'       => 'Regular',
                'title_ru'       => 'Постоянный',
                'description_en' => 'Be active on 30 different days',
                'description_ru' => 'Будьте активны 30 разных дней',
                'icon'           => 'Clock',
                'rules'          => json_encode([['metric' => 'days_active', 'operator' => '>=', 'value' => 30]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'regular',
                'type'           => 'base',
                'tier'           => 'gold',
                'category'       => 'consistency',
                'title_en'       => 'Regular',
                'title_ru'       => 'Постоянный',
                'description_en' => 'Be active on 100 different days',
                'description_ru' => 'Будьте активны 100 разных дней',
                'icon'           => 'Clock',
                'rules'          => json_encode([['metric' => 'days_active', 'operator' => '>=', 'value' => 100]]),
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'streak',
                'type'           => 'base',
                'tier'           => 'bronze',
                'category'       => 'consistency',
                'title_en'       => 'Streak',
                'title_ru'       => 'Серия',
                'description_en' => 'Log in 7 days in a row',
                'description_ru' => 'Заходите 7 дней подряд',
                'icon'           => 'Flame',
                'rules'          => json_encode([['metric' => 'login_streak', 'operator' => '>=', 'value' => 7]]),
                'xp_bonus'       => 10,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'streak',
                'type'           => 'base',
                'tier'           => 'silver',
                'category'       => 'consistency',
                'title_en'       => 'Streak',
                'title_ru'       => 'Серия',
                'description_en' => 'Log in 30 days in a row',
                'description_ru' => 'Заходите 30 дней подряд',
                'icon'           => 'Flame',
                'rules'          => json_encode([['metric' => 'login_streak', 'operator' => '>=', 'value' => 30]]),
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],

            // --- Seasonal ---
            [
                'group_slug'     => 'spring_explorer_2026',
                'type'           => 'seasonal',
                'tier'           => 'silver',
                'category'       => 'seasonal',
                'title_en'       => 'Spring Explorer 2026',
                'title_ru'       => 'Весенний исследователь 2026',
                'description_en' => 'Visit 10 nature and 10 park places in spring 2026',
                'description_ru' => 'Посетите 10 природных мест и 10 парков весной 2026',
                'icon'           => 'Map',
                'rules'          => json_encode([
                    ['metric' => 'places_visited', 'operator' => '>=', 'value' => 10, 'filter' => ['category_id' => '5']],
                    ['metric' => 'places_visited', 'operator' => '>=', 'value' => 10, 'filter' => ['category_id' => '8']],
                ]),
                'season_start'   => '2026-03-01 00:00:00',
                'season_end'     => '2026-05-31 23:59:59',
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'summer_photographer_2026',
                'type'           => 'seasonal',
                'tier'           => 'gold',
                'category'       => 'seasonal',
                'title_en'       => 'Summer Photographer 2026',
                'title_ru'       => 'Летний фотограф 2026',
                'description_en' => 'Upload 50 photos in summer 2026',
                'description_ru' => 'Загрузите 50 фотографий летом 2026',
                'icon'           => 'Camera',
                'rules'          => json_encode([
                    ['metric' => 'photos_uploaded', 'operator' => '>=', 'value' => 50],
                ]),
                'season_start'   => '2026-06-01 00:00:00',
                'season_end'     => '2026-08-31 23:59:59',
                'xp_bonus'       => 50,
                'sort_order'     => ++$sort,
            ],
            [
                'group_slug'     => 'autumn_curator_2026',
                'type'           => 'seasonal',
                'tier'           => 'silver',
                'category'       => 'seasonal',
                'title_en'       => 'Autumn Curator 2026',
                'title_ru'       => 'Осенний куратор 2026',
                'description_en' => 'Edit 20 places and give 30 ratings in autumn 2026',
                'description_ru' => 'Отредактируйте 20 мест и поставьте 30 оценок осенью 2026',
                'icon'           => 'Pencil',
                'rules'          => json_encode([
                    ['metric' => 'places_edited', 'operator' => '>=', 'value' => 20],
                    ['metric' => 'ratings_given', 'operator' => '>=', 'value' => 30],
                ]),
                'season_start'   => '2026-09-01 00:00:00',
                'season_end'     => '2026-11-30 23:59:59',
                'xp_bonus'       => 25,
                'sort_order'     => ++$sort,
            ],
        ];

        foreach ($data as &$row) {
            $row['id']         = substr(md5($row['group_slug'] . '_' . $row['tier']), 0, 12);
            $row['created_at'] = $now;
            $row['updated_at'] = $now;
            $row['is_active']  = 1;
            $row['image']      = null;

            if (!isset($row['season_start'])) {
                $row['season_start'] = null;
            }
            if (!isset($row['season_end'])) {
                $row['season_end'] = null;
            }
        }
        unset($row);

        $this->db->table('achievements')->insertBatch($data);
    }
}
